name = "hono-app"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjQyZDg1NmYtOGE4YS00NzUxLTg4YTAtMDVkY2JjMmZiYjAxIiwidGVuYW50X2lkIjoiN2E4YTZhYWRkYjcwMjIwYTZjYjE0YzE2NzYwZGViZTdiYzlkYzg4YTA2ZGY3YTA1OWIyNGQ1Mjk1NzZjNWU0OSIsImludGVybmFsX3NlY3JldCI6IjM3MGVmOWFlLWNhYjItNDhlMi05YjZjLTJjYTEyZDIyZDFjMCJ9.G9r5nRdIuhKgLZEtaFuF2nNxKplkOMdckAp1XEUUTEU"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
