version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=badsecret
      - POSTGRES_DB=itesting
    ports:
      - "5432:5432"
